import './globals.scss';
import Header from './header';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body>
                <Header />
                <main id='qie-app'>{children}</main>
            </body>
        </html>
    );
}
